### ISSUE TITLE
Set up webhook to auto-deploy after PR merge

### ISSUE THREAD

**Issue by joneslee85** [foundeo/content-security-policy.com#1]
as title, you should look into a free CI like TravisCI for such job

OR

you can use GitHub Page that would save you cost and time for maintainance

**Comment by pfreitag** [comment]
Thanks for the suggestion - I have something setup to auto-deploy merges already. I am familiar with TravisCI it is awesome.

I thought about using github pages, but I want to send `Content-Security-Policy` headers back, and I don't know of a way to do that with GitHub Pages (I'd rather avoid the meta CSP).
