### ISSUE TITLE
child-src now deprecated, use frame-src and worker-src instead

### ISSUE THREAD

**Issue by Malvoz** [foundeo/content-security-policy.com#18]
I just wanted to give a heads up: the **'frame-src' has been undeprecated**, while **'worker-src'** has been added to the W3 spec and the **child-src has been deprecated** (still used as fallback for both 'worker-src' and 'frame-src', which in turn falls back to 'default-src').

**Comment by Malvoz** [comment]
I should leave this open for others to find.

**Comment by pfreitag** [comment]
Updated with CSP3 info
