### ISSUE TITLE
frame-src is not deprecated

### ISSUE THREAD

**Issue by kevna** [foundeo/content-security-policy.com#24]
The site says that frame-src is deprecated in favour of child-src when this is not the case

According to the W3C child-src is deprecated in favour of frame-src and worker-src

W3C: https://w3c.github.io/webappsec-csp/#directive-child-src

**Comment by john-harding** [comment]
Just saw this as well.  While frame-src was originally deprecated in favor of child-src, this was reversed.

**Comment by pfreitag** [comment]
Fixed
