### ISSUE TITLE
Ignore „'unsafe-inline'“ loaded in script-src: 'strict-dynamic'

### ISSUE THREAD

**Issue by Scorpions95** [foundeo/content-security-policy.com#29]
i have follwing issue with my forum
https://i.imgur.com/FRfHKEE.png
i remove my adblocker and trackers

```
Content Security Policy: Ignore of „'unsafe-inline'“ loaded in script-src: 'strict-dynamic'
Content Security Policy: Ignore of  „https:“ loaded in script-src: 'strict-dynamic'
Content Security Policy: Ignore of  „http:“ loaded in script-src: 'strict-dynamic
```
@pfreitag 
how can i fix it?

**Comment by pfreitag** [comment]
The strict-dynamic directive causes unsafe-inline and others to be ignored, see: https://content-security-policy.com/unsafe-inline/
