### ISSUE TITLE
Can't properly load site in Safari 9.1

### ISSUE THREAD

**Issue by iamthechad** [foundeo/content-security-policy.com#3]
Ironically, I can't load this site in Safari 9.1 (OS X 10.11.4) due to CSP issues:

`Refused to load the stylesheet 'https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/readable/bootstrap.min.css' because it violates the following Content Security Policy directive: "style-src 'self' maxcdn.bootstrapcdn.com fonts.googleapis.com".`

`Refused to load the stylesheet 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' because it violates the following Content Security Policy directive: "style-src 'self' maxcdn.bootstrapcdn.com fonts.googleapis.com".`

It looks like `maxcdn.bootstrapcdn.com` should be allowed by the policy.

**Comment by pfreitag** [comment]
Thanks for reporting the issue @iamthechad the `Content-Security-Policy` header did include `maxcdn.boostrapcdn.com` but since the stylesheet was loaded over HTTPS and the site was running over port 80 I had to explicitly match the scheme in the CSP.

**Comment by iamthechad** [comment]
Duh. I should have checked for the HTTP/HTTPS mismatch. Thanks for the update!

**Comment by pfreitag** [comment]
Yes, one of these days I will get around to moving the site over to https, that would have also fixed the issue.
