### ISSUE TITLE
Content-Security-Policy: sandbox in Firefox

### ISSUE THREAD

**Issue by xnyhps** [foundeo/content-security-policy.com#4]
Support for "Content-Security-Policy: sandbox" landed in Firefox [last week](https://bugzilla.mozilla.org/show_bug.cgi?id=671389#c329), but the page on content-security-policy.com claims it is supported in "Firefox 23+", I don't think that can be right.

**Comment by pfreitag** [comment]
Good catch @xnyhps - it looks like support will land in Firefox 50 from what I can tell, is that your understanding as well?
